
  Preparing the environment for use of 2020 stage.

The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) Stages/2020
Setting HOROVOD_MPI_THREADS_DISABLE=1. 
cpu_bind=NONE - jrc0385, task  1  1 [32320]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  0  0 [32323]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  2  2 [32321]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  3  3 [32322]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0385: task 1: Terminated
srun: error: jrc0385: tasks 2-3: Exited with exit code 1
srun: Force Terminated job step 10176020.0
cpu_bind=NONE - jrc0385, task  3  3 [3669]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  1  1 [3670]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  2  2 [3671]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  0  0 [3672]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0385: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0385, task  1  1 [5989]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  2  2 [5988]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  3  3 [5990]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  0  0 [5991]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 993, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0385: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0385, task  0  0 [8212]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  1  1 [8209]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  3  3 [8210]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0385, task  2  2 [8208]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
srun: Job step aborted: Waiting up to 6 seconds for job step to finish.
srun: error: jrc0385: tasks 0-3: Terminated
srun: error: Slurm job 10176020 has expired
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 10176020
srun: error: Slurm job 10176020 has expired
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 10176020
srun: error: Slurm job 10176020 has expired
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 10176020
srun: error: Slurm job 10176020 has expired
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 10176020
srun: error: Slurm job 10176020 has expired
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 10176020
srun: error: Slurm job 10176020 has expired
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 10176020
