
  Preparing the environment for use of requested stage ( 2020 ).

The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) Stages/2020
Setting HOROVOD_MPI_THREADS_DISABLE=1. 
cpu_bind=NONE - jrc0229, task  0  0 [9737]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0229, task  1  1 [9736]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0229, task  3  3 [9738]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0229, task  2  2 [9739]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "main.py", line 967, in <module>
Traceback (most recent call last):
  File "main.py", line 967, in <module>
Traceback (most recent call last):
  File "main.py", line 967, in <module>
    model, lossar, time_elapsed = train_model(smodel, optimizer)
  File "main.py", line 481, in train_model
    trainit(lframe, train_part, opt.bs,
  File "main.py", line 469, in trainit
    model, lossar, time_elapsed = train_model(smodel, optimizer)
  File "main.py", line 481, in train_model
    model, lossar, time_elapsed = train_model(smodel, optimizer)
  File "main.py", line 481, in train_model
    prmatw, bigm, matw, batchsum, lossoutdir, GTw
UnboundLocalError: local variable 'batchsum' referenced before assignment
    trainit(lframe, train_part, opt.bs,
  File "main.py", line 469, in trainit
    trainit(lframe, train_part, opt.bs,
  File "main.py", line 469, in trainit
    prmatw, bigm, matw, batchsum, lossoutdir, GTw
UnboundLocalError: local variable 'batchsum' referenced before assignment
    prmatw, bigm, matw, batchsum, lossoutdir, GTw
UnboundLocalError: local variable 'batchsum' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 967, in <module>
    model, lossar, time_elapsed = train_model(smodel, optimizer)
  File "main.py", line 493, in train_model
    dataloaders = {x: t.utils.data.DataLoader(
  File "main.py", line 496, in <dictcomp>
    worker_init_fn=seed_worker,
NameError: name 'seed_worker' is not defined
srun: error: jrc0229: tasks 0-3: Exited with exit code 1
